# Generated by Django 5.1.11 on 2025-07-09 16:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode_user_is_phone_verified_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCodeSnippet',
            fields=[
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.otpcode',),
        ),
        migrations.CreateModel(
            name='UserSnippet',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('moderator', 'Moderator')], default='user', help_text='User role in the system', max_length=10),
        ),
    ]
